config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main' ,to: 'users#login'
  post 'main' , to: 'users#check' , as: "check"
  get 'feed', to: 'users#feed'
  get "profile/:name", to: "users#viewUser"
  post "profile/:name", to: "users#manageFollow", as: "manageFollow"

  post "like", to: "users#like"
  post "unlike", to: "users#unlike"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :follower, class_name: 'User'
    belongs_to :followee, class_name: 'User'
    validates :follower_id, uniqueness: { scope: :followee_id }
    validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes

  def get_likers
    return User.where(:id => self.likes.pluck('likeUser')).pluck('name')
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	validates :email, uniqueness: true
  	validates :name, uniqueness: true
  	validates :name, :email, :password, presence: true
	has_secure_password

	has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  	has_many :followees, through: :followed_users
  	has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  	has_many :followers, through: :following_users

  	def get_feed_post
  	@user = self
  	@feedpost = Array.new
  	User.find(@user.id).followees.each do |followee|
		followee.posts.each do |post|
			@feedpost.push(post)
		end
	end
	@feedpost = @feedpost.sort_by{ |created_at| created_at }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :logged_in
  before_action :is_current_user, only: %i[ create update]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    if(session[:user_id]!= nil)
      @post.user_id = Integer(session[:user_id])
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def logged_in
      if(session[:user_id])
       return true
      else
       redirect_to main_path, alert: "Please Login"
      end
  end
    def is_current_user
      if(session[:user_id].to_s == params[:post][:user_id])
        return true
      else
        redirect_to feed_path, alert: "You cant create/edit other users posts"
      end
    end 
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:message, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy ]
  before_action :logged_in, except: %i[ login check new create]
  before_action :is_current_user, only: %i[ show edit update destroy]


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def login
    @user = User.new
    session[:user_id] = nil
  end

  def check
    @commit = params[:commit]
    @umail = params[:user][:email]
    @upass = params[:user][:password]
    if(@commit == 'Login')
      @found = false
      @u = User.find_by(email:@umail)
      if(@u && @u.authenticate(@upass))
          redirect_to feed_path, notice: "Login successfully."
          @found = true
          session[:user_id] = @u.id
      end
      if(@found == false)
        redirect_to main_path, alert: "Incorrect Email or Password."
      end
    elsif(@commit == 'Register')
      redirect_to new_user_path
    end
  end



  def feed
    @user = User.find(session[:user_id])  
    @feedpost = @user.get_feed_post

  end


  def viewUser
    @name = params[:name]
    @user = User.find_by(name:@name)
    if(@user == nil)
      redirect_to feed_path, alert: "User not found."
    end
  end

  def manageFollow
    @commit = params[:commit]
    @follower_id = session[:user_id]
    @followee_id = params[:follow][:followee_id]
    if(@commit == 'Follow')
      f = Follow.create(:follower_id => @follower_id, :followee_id => @followee_id)
    end
    if(@commit == 'Unfollow')
      Follow.find_by(follower_id: @follower_id, followee: @followee_id).destroy
    end
    redirect_back(fallback_location: "profile/:name")
  end

  def like
    @pid = params[:pid]
    Like.create(post_id: @pid, likeUser: session[:user_id])
    redirect_to feed_path, notice: "liked"


  end

  def unlike
    @pid = params[:pid]
    Like.find_by(post_id: @pid,likeUser: session[:user_id]).destroy
    redirect_back(fallback_location: "feed")

  end

  private
    def logged_in
      if(session[:user_id])
       return true
      else
       redirect_to main_path, alert: "Please Login"
      end
    end

    def is_current_user
      if(session[:user_id].to_s == params[:id])
        return true
      else
        redirect_to feed_path, alert: "You can't view/edit/destroy other users account"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"} LOGO
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "/main"} Main
        %li.nav-item
          %a.nav-link{:href => "/feed"} feed
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            See our database!
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "/users"} Users
            %li
              %a.dropdown-item{:href => "/posts"} Posts
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Nothing here
        %li.nav-item
          %a.nav-link.disabled Don't know why it's here
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Find something", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Class7
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{href:"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", rel:"stylesheet" ,integrity:"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" , crossorigin:"anonymous"}
    %script{src:"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js", integrity:"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" ,crossorigin:"anonymous"}
    %script{src:"https://code.jquery.com/jquery-3.6.0.min.js"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    .container
      = yield

app/views/posts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :message
    = f.input :user_id

  .form-actions
    = f.button :submit ,class: 'btn btn-outline-dark mt-2'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Message
      %th User
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.message
        %td= post.user_id
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', feed_path , class: 'btn btn-outline-dark mt-2'

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @post.message
%p
  %b User:
  = @post.user_id

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/_Invalid.html.erb
<h1> Invalid email or password </h1>
<%= link_to 'Back', main_path %>

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password

  .form-actions
    = f.button :submit ,class: 'btn btn-outline-dark mt-2'

app/views/users/_likeModal.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modalTitle", :role=>"dialog", :tabindex=> "-1",id: "likeModal"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#modalTitle.modal-title See who like this Post
      .modal-body
        #ul.list-group.list-group-flush#likeduser
      .modal-footer
        %button.btn.btn-secondary.closemodalbutton{"data-dismiss" => "modal", :type => "button"} Close
  }

:javascript
  $(document).ready(function(){

    $(".wholikebutton").click(function(){
      $('#likeModal').modal("show")
      let likers = $(this).attr("likers").split(" ");
        $("#likeduser").html(likers.map(name =>
        '<li class="list-group-item" data-bs-dismiss="modal"><h6><a
        style="text-decoration: none;"
        href="/profile/'+name+'">'+name+'</a></h6></li>'
      ))
    });

    $(".closemodalbutton").click(function(){
      $('#likeModal').modal("hide");
    });

  });

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user

= link_to 'Back', users_path

app/views/users/feed.html.haml
%p#notice= notice
%p#alert= alert
%h1 See your new feed
= render 'likeModal'

.container
  .row
    .col-11
      -@feedpost.each do |post|
        .col
          .d-flex.p-2.border.border-dark.rounded.mt-3
            Username : #{User.find(post.user_id).name} 
            <br>
            Message : #{post.message} 
            <br>

            .col
            - if Like.find_by(post_id: post.id,likeUser: session[:user_id]) == nil
              = button_to 'Like', '/like', params: {pid: post.id}, class: 'btn btn-dark'
            - else
              = button_to 'Unlike', '/unlike', params: {pid: post.id}, class: 'btn btn-outline-dark'
            %button.btn.btn-primary.wholikebutton{"data-target" => "#likeModal","data-toggle"=>"modal", :type => "button","likers"=>"#{post.get_likers}"} total like : #{post.likes.length}
    .col-1
      = link_to 'Post', :new_post, class: 'btn btn-outline-dark'

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/login.html.haml
%h1 LogIn to microTwitter
%p#alert= alert
= simple_form_for(@user, :url => check_path, :method => :post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :email
    = f.input :password

  %p
  .form-actions
    = f.submit 'Login' , class: 'btn btn-outline-dark mt-2'
    = f.submit 'Register', class: 'btn btn-outline-dark mt-2'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Cancel', main_path , class: 'btn btn-outline-dark mt-2'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/users/viewUser.html.haml
%p#notice= notice
%h1  #{@name}'s profile

.container
  = render 'likeModal'
  .row
    .col-11
      - @user.posts.each do |post|
        .d-flex.p-2.border.border-dark.rounded.mt-3 
          Message : #{post.message} <br> 
          Created-at : #{post.created_at} <br>
          .col
          - if Like.find_by(post_id: post.id,likeUser: session[:user_id]) == nil
            = button_to 'Like', '/like', params: {pid: post.id}, class: 'btn btn-dark'
          - else
            = button_to 'Unlike', '/unlike', params: {pid: post.id}, class: 'btn btn-outline-dark'
          %button.btn.btn-primary.wholikebutton{"data-target" => "#likeModal","data-toggle"=>"modal", :type => "button","likers"=>"#{post.get_likers}"} total like : #{post.likes.length}    
    .col-1
      = simple_form_for(Follow.new, :url => manageFollow_url, :method => :post) do |f|
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
        .form-inputs
          = f.hidden_field :followee_id, value: @user.id

        %p
        .form-actions
          - if Follow.find_by(follower_id: session[:user_id], followee: @user.id) == nil
            = f.submit 'Follow', class: 'btn btn-dark'
          - else
            = f.submit 'Unfollow', class: 'btn btn-outline-dark'